### PR TITLE
Added editorconfig file.

### PR DESCRIPTION
**Pull request by richardjrossiii**
This allows for a consistent, cross-platform approach to at least handle line endings and newlines+spaces.

Depends on #96.

### CODE REVIEW

**Comment by hallucinogen** [comment]
Any instructions to how to use `.editorconfig`?

**Comment by richardjrossiii** [comment]
http://editorconfig.org. There's a VS plugin that I'd recommend installing, as well as it will play nice with vim/emacs, etc.

**Comment by hallucinogen** [comment]
Got it. Can you add that to https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/CONTRIBUTING.md under `Style Guide`?

**Comment by richardjrossiii** [comment]
@hallucinogen Done, take a look.

**Comment by hallucinogen** [comment]
Perfecto

**Pull request merged**
