### PR TITLE
Changed badge access to run on the main thread, fixes issues where in…

### PR DESCRIPTION
**Pull request by IkeTheDestroyer**
…stallation is not created in Start or Awake

### CODE REVIEW

**Comment by richardjrossiii** [comment]
Thanks for the PR! Since #42, we have dropped support for unity 4, so this code will need to be cleaned up anyhow.

If you're willing to clean it up and not use `PropertyInfo` and friends, then let me know and I'll be happy to merge it with that cleaned up.

Otherwise, when I clean up ParseInstallation for Unity 5, I'll make sure I make badge access happen on the main thread.

**Comment by IkeTheDestroyer** [comment]
I cleaned up the code, if it is still not up to standard I'll let you do the rest.  Cheers

**Comment by richardjrossiii** [comment]
Looks awesome! 2 (extreeeemly) minor things:

1. Can you squash the commits into one commit?(See http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git)
2. Can you replace your usage of tabs with spaces? Our code style is 2 spaces.

Excited for this PR! Thanks for all your help!

**Comment by richardjrossiii** [comment]
Just checked in. Everything looks good to go, if you can just squash the commits together, then I can merge it!

**Comment by IkeTheDestroyer** [comment]
Squashed

**Pull request merged**
