### PR TITLE
Track push notification open count for windows phone and winrt

### PR DESCRIPTION
**Pull request by Julien-Mialon**
Hello, 

I implemented the hash calculation on push notification to track open count.
Relative to this bug : https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/162

I only did for windows phone and WinRT since I don't really know how it works on other platform. But the ParseAnalyticUtilities.cs class is available in the PCL to easily implement on other platforms if needed.

### CODE REVIEW

**Comment by richardjrossiii** [comment]
This looks good, although we're actually currently in internal discussions to perhaps have the server send the hash on Windows platforms, just like it currently does on android.

Out of curiosity, where did the MD5 implementation come from? We wouldn't be able to accept it unless we verify that the license is compatible with ours.

**Comment by Julien-Mialon** [comment]
MD5 implementation come from an old article from Microsoft that I can't find online anymore. I think it was given to be used on Windows Phone 7.

**Comment by richardjrossiii** [comment]
Hey guys - I just heard back from our backend team. The missing `push_hash` is actually their bug and not ours (the reasons why iOS was calculating it manually are long, boring and basically boil down to rushing a product out the door). 

We're going to ship a fix for this to `parse.com` shortly, which will make this PR obsolete.

Sorry for all of the confusion that's been surrounding this issue.

**Comment by Julien-Mialon** [comment]
Ok, good to know a fix is coming :+1:

**Comment by bnham** [comment]
Here is what we've done here:

1. On the server, /1/events now supports AppOpened tracking by push_id.
2. All pushes now receive the push id in the JSON payload (in the key "parsePushId"). The SDKs (including the Windows SDK) will now use this to track app opens.

Richard is working on (2).

**Pull request closed without merging**
